### ISSUE TITLE
Eroare conectare la Modul SD

### ISSUE THREAD

**Issue by FilipLupaescu** [GroundStudio/GroundStudio_Carbon_V3#1]
>Pasul 4 - Realizarea conexiunilor si incarcarea codului de test
>
>Conectati placa de dezvoltare si modulul microSD:
>
>Carbon V3 ______________ microSD
>              5V______________VCC
>           GND______________GND
>              13______________SDO
>              12______________SDI
>              14______________SCK
>              15______________CS

Când rulez programul din exemplul pentru a testa modulul SD, în primul rând când modulul e conectat primesc eroarea:
`WARNING: Failed to communicate with the flash chip, read/write operations will fail. Try checking the chip connections or removing any other hardware connected to IOs.`
pe site-ul [espressif](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/sd_pullup_requirements.html#strapping-conflicts-dat2) spune:
>On boards using the internal regulator and a 3.3 V flash chip, GPIO12 must be pulled low at reset. This is incompatible with the SD card >operation.

Dacă scot pinul 12 si il conectez doar după reset:

	rst:0x10 (RTCWDT_RTC_RESET),boot:0x37 (SPI_FAST_FLASH_BOOT)
	14:41:31.868 > invalid header: 0xffffffff
	14:41:31.912 > invalid header: 0xffffffff
	14:41:31.957 > invalid header: 0xffffffff

De aceea am încercat cu alți pini pentru SPI, `spiSD.begin(14, 13, 25, SD_CS); // CLK, MISO, MOSI, SS` (apropo ați greșit ordinea în acest comment în exemplu), dar priesc alte erori:

	14:50:15.332 > [   769][E][sd_diskio.cpp:802] sdcard_mount(): f_mount failed: (3) The physical drive cannot work
	14:50:15.832 > [  1269][E][sd_diskio.cpp:126] sdSelectCard(): Select Failed
	14:50:15.835 > Card Mount Failed

M-ați putea ajuta? Vă mulțumesc.

----------

>Pasul 4 - Realizarea conexiunilor si incarcarea codului de test
>
>Conectati placa de dezvoltare si modulul microSD:
>
>Carbon V3 ______________ microSD
>              5V______________VCC
>           GND______________GND
>              13______________SDO
>              12______________SDI
>              14______________SCK
>              15______________CS

When I run the program to test the SD module, first, when the module is connected, I receive the error:
`WARNING: Failed to communicate with the flash chip, read/write operations will fail. Try checking the chip connections or removing any other hardware connected to IOs.`
    On the [Espressif website](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/sd_pullup_requirements.html#strapping-conflicts-dat2), it says:
>On boards using the internal regulator and a 3.3 V flash chip, GPIO12 must be pulled low at reset. This is incompatible with the SD card >operation.

If I remove pin 12 and connect it only after reset:

	rst:0x10 (RTCWDT_RTC_RESET),boot:0x37 (SPI_FAST_FLASH_BOOT)
	14:41:31.868 > invalid header: 0xffffffff
	14:41:31.912 > invalid header: 0xffffffff
	14:41:31.957 > invalid header: 0xffffffff

That's why I tried using other pins for SPI, `spiSD.begin(14, 13, 25, SD_CS); // CLK, MISO, MOSI, SS` (by the way, you made a mistake in the pin order in this comment in the example), but I still get an error:

    14:50:15.332 > [ 769][E][sd_diskio.cpp:802] sdcard_mount(): f_mount failed: (3) The physical drive cannot work
    14:50:15.832 > [ 1269][E][sd_diskio.cpp:126] sdSelectCard(): Select Failed
    14:50:15.835 > Card Mount Failed

 Can you help me with these errors? Thank you.

**Comment by victor1115** [comment]
Bună ziua,

      Ne cerem scuze pentru problemele întâmpinate.
      Este foarte important pentru noi să diagnosticăm orice problemă de producție iar pentru aceasta avem nevoie de mai multe informații despre modul în care ați efectuat testarea acestora:

- poze cu conexiunile fizice realizate de dvs. (nu diagrame), eventual clipuri dacă e cazul (nu vrem o descriere în text a montajului ci poze sau clipuri).
- setarile din Arduino, meniul tools.
- poza cu portul conectat în “Device manager”
- codul rulat
- poze cu ieșirea codului (ce afișează în serial monitor) și conținutul cardului după rularea codului.

Numai bine,
Ardushop.ro
Victor Nicula

**Comment by FilipLupaescu** [comment]
Bună,

Aici sunt conexiunile după cum este specificat pe ArduShop.ro:

![WIRING_12](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/73e959ae-b99b-44a1-8189-7afec1b77b97)

În acest mod nu pot încărca codul, primesc acest mesaj la output:

![OUTPUT_FLASH_ERROR](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/824c7b0a-567d-4eb3-aa41-9d8dc0823af9)

Dacă deconectez pinul 12 și îl conectez după uploadarea codului, am aceasta în Serial Monitor: 

![OUTPUT_INVALID_HEADER](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/15cd5f92-13ab-475f-8155-0f84c303a8f3)

Pentru a putea rula codul, am folosit pinul 26 în loc de 12:

![WIRING_26](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/33b05ddd-5056-4def-a7e0-cd16e8d454c4)

și primesc aceasta în Serial Monitor:

![OUTPUT_CARD_MOUNT_FAILED](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/d3375f72-6348-4a96-a843-baba1efd1d69)

Acesta este cardul folosit, formatat in FAT32:

![SD_CARD](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/9a76d263-6259-4fb6-9220-15926f691794)
![CARD_FORMAT](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/e38aa351-9121-40aa-b461-82316e84dbe4)

Setările din Arduino->Tools:

![ARDUINO_TOOLS](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/2c3b2522-d6d2-4d36-beff-3a4bf53369ba)

Portul conectat din Device Manager:

![DEVICE_MANAGER_PORT](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/9d82f642-9625-46d9-85dd-31d4748cf75f)


Codul folosit este identic cu cel din exemplu cu singura modificare fiind la `Serial.begin(115200);` în loc de 9600, pentru a putea vedea boot log ("invalid header" când GPIO12 e conectat la Modulul SD), și `spiSD.begin(14, 13, 26, SD_CS);` 26 în loc de 12 desigur.
```cpp
#include "FS.h"
#include "SD.h"
#include "SPI.h"

SPIClass spiSD(HSPI);

#define SD_CS 15

void writeFile(fs::FS &fs, const char * path, const char * message){
    Serial.printf("Writing file: %s\n", path);

    File file = fs.open(path, FILE_WRITE);
    if(!file){
        Serial.println("Failed to open file for writing");
        return;
    }
    if(file.print(message)){
        Serial.println("File written");
    } else {
        Serial.println("Write failed");
    }
    file.close();
}

void setup()
{
  Serial.begin(115200);
  Serial.println();
  SPI.end(); 
  spiSD.begin(14, 13, 26, SD_CS); //CLK,MOSI,MISO,SS
  if (!SD.begin(SD_CS, spiSD))
  {
    Serial.println("Card Mount Failed");
    return;
  }
  else
  {
    Serial.println("Card Mount Successful");
  }

  uint8_t cardType = SD.cardType();

  Serial.print("SD Card Type: ");
  if(cardType == CARD_MMC){
        Serial.println("MMC");
    } else if(cardType == CARD_SD){
        Serial.println("SDSC");
    } else if(cardType == CARD_SDHC){
        Serial.println("SDHC");
    } else {
        Serial.println("UNKNOWN");
    }

    uint64_t cardSize = SD.cardSize() / (1024 * 1024);
    Serial.printf("SD Card Size: %lluMB\n", cardSize);
    
  writeFile(SD, "/hello V3.txt", "Hello V3");
  Serial.printf("Total space: %lluMB\n", SD.totalBytes() / (1024 * 1024));
  Serial.printf("Used space: %lluMB\n", SD.usedBytes() / (1024 * 1024));
}

void loop()
{ }
```

Cardul nu conține nimic după rularea codului:

![image](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/8f67be67-e8ee-47a9-9f4f-b2ad5fccf35a)

Vă mulțumesc pentru ajutor,
Filip

**Comment by victor1115** [comment]
Bună ziua,

Ne cerem scuze pentru răspunsul întârziat.
Din testele noastre am observat că eroarea este cauzată de ordinea pinilor în spiSD.begin de la linia 30.

Vă rugăm să modificați această linie astfel:
Înainte: spiSD.begin(14, 13, 12, SD_CS); //CLK,MOSI,MISO,SS
După: spiSD.begin(14, 12, 13, SD_CS); //SCK, MISO, MOSI, SS

Conexiunile hardware rămân neschimbate, doar această linie trebuie modificată.
După încărcarea codului vă rugăm să reveniți cu rezultatul obținut de dvs.

Numai bine,
Ardushop.ro
Victor Nicula

**Comment by FilipLupaescu** [comment]
Bună,

Cu `spiSD.begin(14, 12, 13, SD_CS); //SCK, MISO, MOSI, SS` e același lucru, nu pot folosi pinul 12.

![image](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/cb6d8b91-de9d-4762-a213-747c0be409a5)

Am folosit în schimb pinul 26 in loc de 12 `spiSD.begin(14, 26, 13, SD_CS); //SCK, MISO, MOSI, SS` și așa funcționează.

![image](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/5274dd1c-f9cc-41b9-a3a3-83fc35523630)

![image](https://github.com/GroundStudio/GroundStudio_Carbon_V3/assets/65253848/e5601b3a-8cce-450d-b327-caa18471060a)

Vă mulțumesc,
Filip
